### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by RainboeStrykr**

### CODE REVIEW

**Comment by foxy4096** [comment]
Well that was unexpected.
The background is getting inverted, nvm.
Imma merge it anyway


well ty 👍

**Comment by foxy4096** [comment]
I am still wondering why did you choose my site
😕

**Comment by RainboeStrykr** [comment]
Not a big deal tho my friend

**Comment by RainboeStrykr** [comment]
🤷‍♂️😀 pardon me

**Pull request merged**
